package backend.reports.util;

import backend.reports.dto.ReportRequest;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;
import com.itextpdf.text.pdf.qrcode.WriterException;
import java.io.ByteArrayOutputStream;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.Map;

public class PdfGeneratorUtil {

    public static byte[] generateReportPdf(ReportRequest request, List<?> dataList, Map<String, Object> stats, String generatedBy) {
        Document document = new Document(PageSize.A4, 36, 36, 54, 54);
        ByteArrayOutputStream out = new ByteArrayOutputStream();

        try {
            PdfWriter writer = PdfWriter.getInstance(document, out);
            
            // Set password protection if requested
            if (request.getPassword() != null && !request.getPassword().isEmpty()) {
                writer.setEncryption(
                    request.getPassword().getBytes(),
                    "owner-sentinel-pass-123".getBytes(),
                    PdfWriter.ALLOW_PRINTING,
                    PdfWriter.ENCRYPTION_AES_128
                );
            }

            // Setup Header, Footer, and Watermark page events
            ReportPageEvents events = new ReportPageEvents(request.getWatermarkText(), generatedBy);
            writer.setPageEvent(events);

            document.open();

            // Font styles
            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 22, BaseColor.DARK_GRAY);
            Font subtitleFont = FontFactory.getFont(FontFactory.HELVETICA, 12, BaseColor.GRAY);
            Font sectionFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 14, new BaseColor(41, 128, 185));
            Font textFont = FontFactory.getFont(FontFactory.HELVETICA, 10, BaseColor.BLACK);
            Font headerFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, BaseColor.WHITE);

            // Title & Header Information
            Paragraph title = new Paragraph("SENTINELCORE ENTERPRISE REPORT", titleFont);
            title.setAlignment(Element.ALIGN_CENTER);
            document.add(title);

            Paragraph subtitle = new Paragraph(request.getReportType().toUpperCase() + " SUMMARY", subtitleFont);
            subtitle.setAlignment(Element.ALIGN_CENTER);
            document.add(subtitle);
            document.add(new Paragraph(" "));

            // Metadata Box
            PdfPTable metaTable = new PdfPTable(2);
            metaTable.setWidthPercentage(100);
            metaTable.setWidths(new float[]{1f, 1f});
            
            metaTable.addCell(createMetaCell("Generated By: " + generatedBy, textFont));
            metaTable.addCell(createMetaCell("Date Generated: " + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss")), textFont));
            
            String filterSummary = buildFilterSummary(request);
            metaTable.addCell(createMetaCell("Filters Applied:\n" + filterSummary, textFont));
            
            // Logo placeholder / vector shapes in PDF
            if (Boolean.TRUE.equals(request.getIncludeLogo())) {
                metaTable.addCell(createLogoCell());
            } else {
                metaTable.addCell(createMetaCell("", textFont));
            }

            document.add(metaTable);
            document.add(new Paragraph(" "));

            // Stats section if available (Dashboard Summary)
            if (stats != null && !stats.isEmpty()) {
                document.add(new Paragraph("Key Summary Metrics", sectionFont));
                document.add(new Paragraph(" "));
                PdfPTable statsTable = new PdfPTable(stats.size());
                statsTable.setWidthPercentage(100);
                
                for (Map.Entry<String, Object> entry : stats.entrySet()) {
                    PdfPCell cell = new PdfPCell(new Paragraph(entry.getKey() + "\n" + entry.getValue(), FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, BaseColor.DARK_GRAY)));
                    cell.setHorizontalAlignment(Element.ALIGN_CENTER);
                    cell.setBackgroundColor(new BaseColor(240, 243, 244));
                    cell.setPadding(10);
                    statsTable.addCell(cell);
                }
                document.add(statsTable);
                document.add(new Paragraph(" "));
            }

            // Main Data Table
            document.add(new Paragraph("Detailed Record Log", sectionFont));
            document.add(new Paragraph(" "));

            if (dataList == null || dataList.isEmpty()) {
                Paragraph emptyMsg = new Paragraph("No records found matching the requested filters.");
                emptyMsg.setAlignment(Element.ALIGN_CENTER);
                document.add(emptyMsg);
            } else {
                PdfPTable dataTable = createDataTable(request.getReportType(), dataList, headerFont, textFont);
                document.add(dataTable);
            }

            document.add(new Paragraph(" "));

            // QR Verification & Signature placeholders
            PdfPTable footerTable = new PdfPTable(2);
            footerTable.setWidthPercentage(100);
            footerTable.setWidths(new float[]{1f, 1.5f});

            // QR Code cell
            if (Boolean.TRUE.equals(request.getIncludeQrCode())) {
                PdfPCell qrCell = new PdfPCell();
                qrCell.setBorder(Rectangle.NO_BORDER);
                try {
                    String qrContent = "https://sentinelcore.com/verify/report?type=" + request.getReportType() + "&time=" + LocalDateTime.now().toString();
                    BarcodeQRCode qrCode = new BarcodeQRCode(qrContent, 75, 75, null);
                    Image qrImage = qrCode.getImage();
                    qrImage.setAlignment(Element.ALIGN_LEFT);
                    qrCell.addElement(new Paragraph("Verify Authenticity:", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 8)));
                    qrCell.addElement(qrImage);
                } catch (Exception e) {
                    qrCell.addElement(new Paragraph("[QR Verification Placeholder]"));
                }
                footerTable.addCell(qrCell);
            } else {
                PdfPCell emptyCell = new PdfPCell();
                emptyCell.setBorder(Rectangle.NO_BORDER);
                footerTable.addCell(emptyCell);
            }

            // Signature block
            if (Boolean.TRUE.equals(request.getIncludeSignaturePlaceholder())) {
                PdfPCell sigCell = new PdfPCell();
                sigCell.setBorder(Rectangle.NO_BORDER);
                sigCell.setHorizontalAlignment(Element.ALIGN_RIGHT);
                Paragraph sigText = new Paragraph("\n\n___________________________\nAuthorized Digital Signature", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 9, BaseColor.DARK_GRAY));
                sigText.setAlignment(Element.ALIGN_RIGHT);
                sigCell.addElement(sigText);
                footerTable.addCell(sigCell);
            } else {
                PdfPCell emptyCell = new PdfPCell();
                emptyCell.setBorder(Rectangle.NO_BORDER);
                footerTable.addCell(emptyCell);
            }

            document.add(footerTable);

            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        return out.toByteArray();
    }

    private static PdfPCell createMetaCell(String text, Font font) {
        PdfPCell cell = new PdfPCell(new Paragraph(text, font));
        cell.setBorder(Rectangle.BOX);
        cell.setPadding(6);
        cell.setBorderColor(BaseColor.LIGHT_GRAY);
        return cell;
    }

    private static PdfPCell createLogoCell() {
        // Create a stylized logo cell using drawing/fonts instead of image dependency
        Paragraph logoText = new Paragraph("SENTINELCORE", FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, new BaseColor(41, 128, 185)));
        logoText.setAlignment(Element.ALIGN_RIGHT);
        Paragraph taglineText = new Paragraph("Threat Intelligence Platform", FontFactory.getFont(FontFactory.HELVETICA_OBLIQUE, 8, BaseColor.GRAY));
        taglineText.setAlignment(Element.ALIGN_RIGHT);
        
        PdfPCell cell = new PdfPCell();
        cell.addElement(logoText);
        cell.addElement(taglineText);
        cell.setBorder(Rectangle.BOX);
        cell.setPadding(6);
        cell.setBorderColor(BaseColor.LIGHT_GRAY);
        cell.setHorizontalAlignment(Element.ALIGN_RIGHT);
        return cell;
    }

    private static String buildFilterSummary(ReportRequest request) {
        StringBuilder sb = new StringBuilder();
        if (request.getStartDate() != null) sb.append("Start: ").append(request.getStartDate().toLocalDate()).append("\n");
        if (request.getEndDate() != null) sb.append("End: ").append(request.getEndDate().toLocalDate()).append("\n");
        if (request.getSeverity() != null && !request.getSeverity().isEmpty()) sb.append("Severity: ").append(request.getSeverity()).append("\n");
        if (request.getIncidentType() != null && !request.getIncidentType().isEmpty()) sb.append("Type: ").append(request.getIncidentType()).append("\n");
        if (request.getStatus() != null && !request.getStatus().isEmpty()) sb.append("Status: ").append(request.getStatus()).append("\n");
        if (sb.length() == 0) return "All records (No filters applied)";
        return sb.toString().trim();
    }

    private static PdfPTable createDataTable(String reportType, List<?> dataList, Font headerFont, Font textFont) {
        // Build tables dynamically based on report types and reflect properties reflection
        if (reportType.equalsIgnoreCase("incident")) {
            PdfPTable table = new PdfPTable(5);
            table.setWidthPercentage(100);
            table.addCell(createHeaderCell("ID", headerFont));
            table.addCell(createHeaderCell("Title", headerFont));
            table.addCell(createHeaderCell("Severity", headerFont));
            table.addCell(createHeaderCell("Status", headerFont));
            table.addCell(createHeaderCell("Created At", headerFont));
            
            for (Object obj : dataList) {
                // Dynamically fetch properties or cast
                Map<?, ?> map = (Map<?, ?>) obj;
                table.addCell(createCell(String.valueOf(map.get("id")), textFont));
                table.addCell(createCell(String.valueOf(map.get("title")), textFont));
                table.addCell(createCell(String.valueOf(map.get("severity")), textFont));
                table.addCell(createCell(String.valueOf(map.get("status")), textFont));
                table.addCell(createCell(String.valueOf(map.get("createdAt")), textFont));
            }
            return table;
        } else if (reportType.equalsIgnoreCase("alert")) {
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.addCell(createHeaderCell("ID", headerFont));
            table.addCell(createHeaderCell("Name", headerFont));
            table.addCell(createHeaderCell("Severity", headerFont));
            table.addCell(createHeaderCell("Status", headerFont));
            
            for (Object obj : dataList) {
                Map<?, ?> map = (Map<?, ?>) obj;
                table.addCell(createCell(String.valueOf(map.get("id")), textFont));
                table.addCell(createCell(String.valueOf(map.get("title")), textFont));
                table.addCell(createCell(String.valueOf(map.get("severity")), textFont));
                table.addCell(createCell(String.valueOf(map.get("status")), textFont));
            }
            return table;
        } else if (reportType.equalsIgnoreCase("compliance")) {
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.addCell(createHeaderCell("Requirement ID", headerFont));
            table.addCell(createHeaderCell("Standard", headerFont));
            table.addCell(createHeaderCell("Requirement Name", headerFont));
            table.addCell(createHeaderCell("Status", headerFont));

            for (Object obj : dataList) {
                Map<?, ?> map = (Map<?, ?>) obj;
                table.addCell(createCell(String.valueOf(map.get("id")), textFont));
                table.addCell(createCell(String.valueOf(map.get("standard")), textFont));
                table.addCell(createCell(String.valueOf(map.get("name")), textFont));
                table.addCell(createCell(String.valueOf(map.get("status")), textFont));
            }
            return table;
        } else { // Audit logs or general
            PdfPTable table = new PdfPTable(4);
            table.setWidthPercentage(100);
            table.addCell(createHeaderCell("Timestamp", headerFont));
            table.addCell(createHeaderCell("User", headerFont));
            table.addCell(createHeaderCell("Action", headerFont));
            table.addCell(createHeaderCell("Details", headerFont));
            
            for (Object obj : dataList) {
                Map<?, ?> map = (Map<?, ?>) obj;
                table.addCell(createCell(String.valueOf(map.get("timestamp")), textFont));
                table.addCell(createCell(String.valueOf(map.get("user")), textFont));
                table.addCell(createCell(String.valueOf(map.get("action")), textFont));
                table.addCell(createCell(String.valueOf(map.get("details")), textFont));
            }
            return table;
        }
    }

    private static PdfPCell createHeaderCell(String text, Font font) {
        PdfPCell cell = new PdfPCell(new Paragraph(text, font));
        cell.setBackgroundColor(new BaseColor(41, 128, 185));
        cell.setPadding(6);
        cell.setHorizontalAlignment(Element.ALIGN_CENTER);
        return cell;
    }

    private static PdfPCell createCell(String text, Font font) {
        PdfPCell cell = new PdfPCell(new Paragraph(text, font));
        cell.setPadding(6);
        return cell;
    }

    // Header, Footer and Watermark Page Events Helper
    private static class ReportPageEvents extends PdfPageEventHelper {
        private final String watermarkText;
        private final String generatedBy;

        public ReportPageEvents(String watermarkText, String generatedBy) {
            this.watermarkText = watermarkText;
            this.generatedBy = generatedBy;
        }

        @Override
        public void onEndPage(PdfWriter writer, Document document) {
            PdfContentByte cb = writer.getDirectContentUnder();
            
            // 1. Watermark
            if (watermarkText != null && !watermarkText.isEmpty()) {
                cb.saveState();
                cb.setColorFill(new BaseColor(220, 220, 220));
                Font font = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 48);
                try {
                    BaseFont bf = font.getCalculatedBaseFont(false);
                    cb.beginText();
                    cb.setFontAndSize(bf, 48);
                    cb.showTextAligned(Element.ALIGN_CENTER, watermarkText, 297, 420, 45);
                    cb.endText();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                cb.restoreState();
            }

            // 2. Footer (Page numbers, Generated by/time)
            PdfContentByte cbOver = writer.getDirectContent();
            cbOver.saveState();
            cbOver.beginText();
            try {
                BaseFont bf = FontFactory.getFont(FontFactory.HELVETICA).getCalculatedBaseFont(false);
                cbOver.setFontAndSize(bf, 8);
                cbOver.setColorFill(BaseColor.GRAY);
                
                // Left aligned footer
                cbOver.showTextAligned(Element.ALIGN_LEFT, "Internal Security Document - SentinelCore", 36, 20, 0);
                
                // Right aligned footer - Page Number
                String pageNumStr = "Page " + writer.getPageNumber();
                cbOver.showTextAligned(Element.ALIGN_RIGHT, pageNumStr, 559, 20, 0);
            } catch (Exception e) {
                e.printStackTrace();
            }
            cbOver.endText();
            cbOver.restoreState();
        }
    }
}
